source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.2'
pod 'SDWebImage', '~> 3.7.2'
pod "TCBlobDownload", '~> 2.1.1'
pod 'MRProgress/AFNetworking', '~> 0.8.2'
pod 'UMengSocialCOM', '~> 5.2.1'
pod 'DTCoreText'
pod 'YYKit', '~> 1.0.6'
